import { ButtonProps } from 'common/keyboardButton/KeyboardButton';


export type Rows = {
    row1: ButtonProps[]
    row2: ButtonProps[]
    row3: ButtonProps[]
    row4: ButtonProps[]
    row5: ButtonProps[]
}

export type Keyboard = {
    [key in string] : Rows
}
export const keyboard: Keyboard = {
  en: {
    row1: [
      { value: '`', value2: '~' },
      { value: '1' },
      { value: '2' },
      { value: '3' },
      { value: '4' },
      { value: '5' },
      { value: '6' },
      { value: '7' },
      { value: '8' },
      { value: '9' },
      { value: '0' },
      { value: '-', value2: '_' },
      { value: '=', value2: '+' },
      { value: '',
        width: '84px',
        value2: 'backspace',
        location:'center_bottom' },
    ],
    row2: [
      { value: '',
        width:'84px',
        value2:'tab',
        location:'start' },
      { value: 'q' },
      { value: 'w' },
      { value: 'e' },
      { value: 'r' },
      { value: 't' },
      { value: 'y' },
      { value: 'u' },
      { value: 'i' },
      { value: 'o' },
      { value: 'p' },
      { value: '[', value2: '{' },
      { value: ']', value2: '}' },
      { value: '\\', value2: '|' },
    ],
    row3: [
      { value: '',
        width:'100px',
        value2:'caps lock',
        location:'start' },
      { value: 'a' },
      { value: 's' },
      { value: 'd' },
      { value: 'f' },
      { value: 'g' },
      { value: 'h' },
      { value: 'j' },
      { value: 'k' },
      { value: 'l' },
      { value: ';', value2: ':' },
      { value: '\'', value2: '"' },
      { value: '\n',
        width:'108px',
        value2:'enter',
        location:'end' }
    ],
    row4: [
      { value: '',
        width:'136px',
        value2:'shift',
        location:'start',
        keyLocation: 1
      },
      { value: 'z' },
      { value: 'x' },
      { value: 'c' },
      { value: 'v' },
      { value: 'b' },
      { value: 'n' },
      { value: 'm' },
      { value: ',', value2: '<' },
      { value: '.', value2: '>' },
      { value: '/', value2: '?' },
      { value: '',
        width:'136px',
        value2:'shift',
        location:'end',
        keyLocation: 2
      }
    ],
    row5: [
      { value: '',
        width:'70px',
        value2:'ctrl',
        location:'start',
        keyLocation: 1
      },
      { value: '',
        width: '70px' },
      { value: '',
        width:'70px',
        value2:'alt',
        location:'start',
        keyLocation: 1
      },
      { value: ' ',
        width:'472px' },
      { value: '',
        width:'70px',
        value2:'alt',
        location:'end',
        keyLocation: 2
      },
      { value: '',
        width:'70px' },
      { value: '',
        width:'70px',
        value2:'ctrl',
        location:'end',
        keyLocation: 2
      },
    ]
  },
  ru: {
    row1: [
      { value: 'ё' },
      { value: '1' },
      { value: '2' },
      { value: '3' },
      { value: '4' },
      { value: '5' },
      { value: '6' },
      { value: '7' },
      { value: '8' },
      { value: '9' },
      { value: '0' },
      { value: '-', value2: '_' },
      { value: '=', value2: '+' },
      { value: '',
        width: '84px',
        value2: 'backspace',
        location:'center_bottom' },
    ],
    row2: [
      { value: '',
        width:'84px',
        value2:'tab',
        location:'start' },
      { value: 'й' },
      { value: 'ц' },
      { value: 'у' },
      { value: 'к' },
      { value: 'е' },
      { value: 'н' },
      { value: 'г' },
      { value: 'ш' },
      { value: 'щ' },
      { value: 'з' },
      { value: 'х' },
      { value: 'ъ' },
      { value: '\\', value2: '/' },
    ],
    row3: [
      { value: '',
        width:'100px',
        value2:'caps lock',
        location:'start' },
      { value: 'ф' },
      { value: 'ы' },
      { value: 'в' },
      { value: 'а' },
      { value: 'п' },
      { value: 'р' },
      { value: 'о' },
      { value: 'л' },
      { value: 'д' },
      { value: 'ж' },
      { value: 'э' },
      { value: '',
        width:'108px',
        value2:'enter',
        location:'end' }
    ],
    row4: [
      { value: '',
        width:'136px',
        value2:'shift',
        location:'start',
        keyLocation: 1
      },
      { value: 'я' },
      { value: 'ч' },
      { value: 'с' },
      { value: 'м' },
      { value: 'и' },
      { value: 'т' },
      { value: 'ь' },
      { value: 'б' },
      { value: 'ю' },
      { value: '.', value2: ',' },
      { value: '',
        width:'136px',
        value2:'shift',
        location:'end',
        keyLocation: 2
      }
    ],
    row5: [
      { value: '',
        width:'70px',
        value2:'ctrl',
        location:'start',
        keyLocation: 2
      },
      { value: '',
        width: '70px' },
      { value: '',
        width:'70px',
        value2:'alt',
        location:'start' },
      { value: '',
        width:'472px' },
      { value: '',
        width:'70px',
        value2:'alt',
        location:'end' },
      { value: '',
        width:'70px' },
      { value: '',
        width:'70px',
        value2:'ctrl',
        location:'end',
        keyLocation: 2
      },
    ]
  }
};
