import { ReactNode } from 'react';
import classes from 'classnames';
import ProgressBarClient from 'common/progressBar/ProgressBarClient';
import KeyBoardSettingsModal from 'components/common/keyboardSettingsModal/KeyBoardSettingsModal';
import ClientProviders from 'components/providers/clientProviders/ClientProviders';
import i18nConfig from 'i18nConfig';
import { dir } from 'i18next';
import type { Metadata } from 'next';
import { Geologica, Ubuntu_Mono } from 'next/font/google';
import './globals.css';
import { cookies } from 'next/headers';
import { ParamsLocale } from 'types/commonTypes';
import '@fontsource-variable/geologica';
import '@fontsource/ubuntu-mono';


const geologica = Geologica({
  subsets: ['latin'],
  weight: ['400', '300'],
  style: ['normal'],
  display: 'swap'
});

const ubuntuMono = Ubuntu_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

interface IRootLayout extends ParamsLocale {
  children: ReactNode;
}
export default async function RootLayout({
  children,
  params: { locale }
}: IRootLayout) {
  const theme = cookies().get('theme')?.value || '';
  return (
    <html lang={locale} dir={dir(locale)} className={classes(geologica.className, ubuntuMono.className)}>
      <body className={theme}>
        <ProgressBarClient />
        {children}
        <ClientProviders>
          <KeyBoardSettingsModal />
        </ClientProviders>
      </body>
    </html>
  );
}
